/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KuFb06IkRPM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Component() {
  return (
    (<footer className="bg-[#1e272e] text-muted-foreground py-8 sm:py-12">
      <div
        className="container max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
        <div className="flex flex-col gap-4">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <MountainIcon className="w-6 h-6" />
            <span className="sr-only">Airbnb</span>
          </Link>
          <div className="text-sm">&copy; 2024 Airbnb, Inc. All rights reserved.</div>
        </div>
        <div className="grid gap-2">
          <h4 className="text-sm font-medium">Hosting</h4>
          <Link
            href="#"
            className="hover:underline hover:underline-offset-2"
            prefetch={false}>
            Why host
          </Link>
          <Link
            href="#"
            className="hover:underline hover:underline-offset-2"
            prefetch={false}>
            Hospitality
          </Link>
          <Link
            href="#"
            className="hover:underline hover:underline-offset-2"
            prefetch={false}>
            Responsible hosting
          </Link>
          <Link
            href="#"
            className="hover:underline hover:underline-offset-2"
            prefetch={false}>
            Community center
          </Link>
        </div>
        <div className="grid gap-2">
          <h4 className="text-sm font-medium">Experiences</h4>
          <Link
            href="#"
            className="hover:underline hover:underline-offset-2"
            prefetch={false}>
            Airbnb Experiences
          </Link>
          <Link
            href="#"
            className="hover:underline hover:underline-offset-2"
            prefetch={false}>
            Airbnb Online Experiences
          </Link>
          <Link
            href="#"
            className="hover:underline hover:underline-offset-2"
            prefetch={false}>
            Gift cards
          </Link>
        </div>
        <div className="grid gap-2">
          <h4 className="text-sm font-medium">Social</h4>
          <div className="flex items-center gap-2">
            <Link
              href="#"
              className="hover:underline hover:underline-offset-2"
              prefetch={false}>
              <TwitterIcon className="w-5 h-5" />
            </Link>
            <Link
              href="#"
              className="hover:underline hover:underline-offset-2"
              prefetch={false}>
              <FacebookIcon className="w-5 h-5" />
            </Link>
            <Link
              href="#"
              className="hover:underline hover:underline-offset-2"
              prefetch={false}>
              <InstagramIcon className="w-5 h-5" />
            </Link>
            <Link
              href="#"
              className="hover:underline hover:underline-offset-2"
              prefetch={false}>
              <LinkedinIcon className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </div>
    </footer>)
  );
}

function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}


function LinkedinIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}
